services:
  auto-priority-api:
    build: .
    ports:
      - "3133:3133" 
    volumes:
      - ./combined.log:/usr/src/app/combined.log
      - ./error.log:/usr/src/app/error.log
    environment:
      NODE_ENV: production
      DATABASE_URL: 
      API_TOKEN: 
      TZ: America/Sao_Paulo
    command: npm start  
    restart: unless-stopped